---
- name: Add all apt repository
  ansible.builtin.command:
    cmd: "add-apt-repository -s -y {{ item }}"
  with_items:
    - main
    - universe
    - restricted
    - multiverse
  become: yes
  become_user: root
  become_method: sudo
  tags:
    - ubuntu
