---
- name: Install common packages for Ubuntu
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"
  become: yes
  become_user: root
  become_method: sudo
  when: ansible_facts['os_family']|lower == 'debian'
  tags:
    - ubuntu

- name: Install common packages for Centos
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  with_items: "{{ packages }}"
  become: yes
  become_user: root
  become_method: sudo
  when: ansible_facts['os_family']|lower == 'redhat'
  tags:
    - centos
